# Generated by Django 3.0.6 on 2021-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered_news',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
