# Generated by Django 3.0.6 on 2021-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsubject',
            name='sector',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
