# Generated by Django 3.0.6 on 2021-06-14 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_searchsubject_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchsubject2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('search_subject', models.CharField(blank=True, max_length=400, unique=True)),
                ('sector', models.CharField(blank=True, max_length=400)),
                ('stakeholder', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'unique_together': {('search_subject', 'stakeholder')},
            },
        ),
    ]
